# Generated by Django 3.0.6 on 2020-06-29 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdditionalRules',
            new_name='AdditionalRule',
        ),
        migrations.RenameModel(
            old_name='BattlePlans',
            new_name='BattlePlan',
        ),
    ]
