# Generated by Django 3.0.6 on 2020-06-30 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0002_auto_20200629_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='additionalrule',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battleplan',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battleplan',
            name='deployment_map',
            field=models.ImageField(default='no-image-found.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='battleplan',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='battleplan',
            name='setup',
            field=models.CharField(default='Enter setup info', max_length=1000),
        ),
        migrations.AddField(
            model_name='battleplan',
            name='victory',
            field=models.CharField(default='Enter victory info', max_length=1000),
        ),
        migrations.AddField(
            model_name='commandability',
            name='battle_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commandability',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commandability',
            name='realm_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commandability',
            name='specific_battle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AddField(
            model_name='commandability',
            name='specific_realm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AddField(
            model_name='realmfeature',
            name='battle_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realmfeature',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realmfeature',
            name='realm_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realmfeature',
            name='specific_battle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AddField(
            model_name='realmfeature',
            name='specific_realm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AddField(
            model_name='spell',
            name='battle_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='realm_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spell',
            name='specific_battle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AddField(
            model_name='spell',
            name='specific_realm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AddField(
            model_name='terrainfeature',
            name='battle_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrainfeature',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrainfeature',
            name='realm_spell',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='terrainfeature',
            name='specific_battle_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AddField(
            model_name='terrainfeature',
            name='specific_realm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AlterField(
            model_name='additionalrule',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='additionalrule',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='battleplan',
            name='aditional_rules',
            field=models.ManyToManyField(to='battle_manager.AdditionalRule'),
        ),
        migrations.AlterField(
            model_name='battleplan',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='battleplan',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commandability',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commandability',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realmfeature',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='realmfeature',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spell',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spell',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='terrainfeature',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='terrainfeature',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
