# Generated by Django 3.0.6 on 2020-06-30 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0003_auto_20200630_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleplan',
            name='battle_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattleType'),
        ),
    ]
