# Generated by Django 3.0.6 on 2020-06-30 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0005_auto_20200630_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalrule',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='battleplan',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commandability',
            name='specific_battle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AlterField(
            model_name='commandability',
            name='specific_realm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AlterField(
            model_name='commandability',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='realmfeature',
            name='specific_battle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AlterField(
            model_name='realmfeature',
            name='specific_realm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AlterField(
            model_name='realmfeature',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spell',
            name='specific_battle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='specific_realm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='terrainfeature',
            name='specific_battle_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattlePlan'),
        ),
        migrations.AlterField(
            model_name='terrainfeature',
            name='specific_realm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Realm'),
        ),
        migrations.AlterField(
            model_name='terrainfeature',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
