# Generated by Django 3.0.6 on 2020-06-30 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0007_auto_20200630_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalrule',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Source'),
        ),
        migrations.AlterField(
            model_name='battleplan',
            name='battle_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.BattleType'),
        ),
        migrations.AlterField(
            model_name='battleplan',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Source'),
        ),
        migrations.AlterField(
            model_name='commandability',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Source'),
        ),
        migrations.AlterField(
            model_name='spell',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Source'),
        ),
        migrations.AlterField(
            model_name='terrainfeature',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='battle_manager.Source'),
        ),
    ]
