# Generated by Django 3.0.6 on 2020-07-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0008_auto_20200630_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battleplan',
            old_name='aditional_rules',
            new_name='additional_rules',
        ),
        migrations.AddField(
            model_name='battleplan',
            name='battle_specific_rules',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
