# Generated by Django 3.0.6 on 2020-07-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0009_auto_20200701_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleplan',
            name='setup',
            field=models.CharField(default='Enter setup info', max_length=2000),
        ),
        migrations.AlterField(
            model_name='battleplan',
            name='victory',
            field=models.CharField(default='Enter victory info', max_length=2000),
        ),
    ]
