# Generated by Django 3.0.6 on 2020-07-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0011_auto_20200701_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrain', models.IntegerField(blank=True)),
                ('battle_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle_manager.BattlePlan')),
                ('realm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle_manager.Realm')),
                ('realm_feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='battle_manager.RealmFeature')),
                ('terrain_feature', models.ManyToManyField(blank=True, to='battle_manager.TerrainFeature')),
            ],
        ),
    ]
