# Generated by Django 3.0.6 on 2020-07-09 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battle_manager', '0012_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='battle_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='battle_manager.BattleType'),
            preserve_default=False,
        ),
    ]
